#!/bin/bash

C3BASEPATH=$( [[ "$(uname -s)" == Darwin ]] && echo "$HOME/open-c3-workspace" || echo "/data" )
. $C3BASEPATH/open-c3/Installer/scripts/multi-os-support.sh

export C3GITBASEURL='https://github.com/open-c3/open-c3/blob/v2.6.0'

echo '# API/文档'
echo ""

./c3mc-dtool-apidoc-make |grep '^## '|grep /|awk '{print $2}' |awk -F'/' '{print $1}'|sort|uniq|c3xargs ./c3mc-dtool-apidoc-make {}
