#!/opt/mydan/perl/bin/perl
use strict;
use warnings;

$|++;

=head1 SYNOPSIS

 $0

=cut


my @x = `find open-c3-code_/*/lib/api -name *.pm`;
chomp @x;

my %data;
for my $x ( @x )
{
    my @cont = `/opt/mydan/perl/bin/perl open-c3-code_/Connector/pp/dtool/c3mc-dtool-apidoc-make-onece '$x'`;
    die "task error: $!" if $?;
    chomp @cont;

    my $title = @cont ? $cont[0] : 'unkown';
    $data{$title} //= [];

    push @{$data{$title}}, @cont;
}

print "# API/文档\n\n";

map{  map{ print "$_\n" }@{$data{$_}}; }sort keys %data;
