#!/bin/bash

echo "# 2TODO/2.列表";
echo "";

export C3GITBASEURL='https://github.com/open-c3/open-c3/blob/v2.6.0'

echo \
  open-c3-code_/    \
  | xargs -n 1 \
  | xargs -i{} bash -c 'grep "C3TODO [0-9][0-9][0-9][0-9][0-9][0-9] " {} -Rl' \
  | grep -v ".swp$" \
  | xargs -i{} bash -c "/opt/mydan/perl/bin/perl open-c3-code_/Connector/pp/dtool/c3mc-dtool-todo-make-onece {} || exit 255"
