#!/bin/bash

C3BASEPATH=$( [[ "$(uname -s)" == Darwin ]] && echo "$HOME/open-c3-workspace" || echo "/data" )
. $C3BASEPATH/open-c3/Installer/scripts/multi-os-support.sh

echo "# 2TODO/2.列表";
echo "";

export C3GITBASEURL='https://github.com/open-c3/open-c3/blob/v2.6.0'

echo \
  open-c3-code_/    \
  | xargs -n 1 \
  | c3xargs bash -c 'grep "C3TODO [0-9][0-9][0-9][0-9][0-9][0-9] " {} -Rl' \
  | grep -v ".swp$" \
  | c3xargs bash -c "perl open-c3-code_/Connector/pp/dtool/c3mc-dtool-todo-make-onece {} || exit 255"
