#!/bin/bash

C3BASEPATH=$( [[ "$(uname -s)" == Darwin ]] && echo "$HOME/open-c3-workspace" || echo "/data" )
. $C3BASEPATH/open-c3/Installer/scripts/multi-os-support.sh

echo "# C3MC/文档";
echo "";

export C3GITBASEURL='https://github.com/open-c3/open-c3/blob/v2.6.0'

find open-c3-code_/Connector/pp -name "c3mc-*" | sort | c3xargs bash -c "perl open-c3-code_/Connector/pp/dtool/c3mc-dtool-c3mcdoc-make-onece  {} || exit 255"

exit 0
