{
 "title": "OPEN-C3",
 "description": "openc3",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "openc3,openc3-cmcm-stage,openc3-cmcm,openc3-orionstar-stage,openc3-orionstar"
   }
  ]
 },
 "panels": [
  {
   "title": "系统错误数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_system_error{job=\"$cluster\"}",
     "legendFormat": "系统错误"
    },
    {
     "expr": "openc3_system_fail{job=\"$cluster\"}",
     "legendFormat": "日志中的错误.[{{host}}]"
    }
   ]
  },
  {
   "title": "reading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_api_reading{job=\"$cluster\"}",
     "legendFormat": "api[{{host}}]"
    },
    {
     "expr": "openc3_ci_reading{job=\"$cluster\"}",
     "legendFormat": "ci[{{host}}]"
    },
    {
     "expr": "openc3_agent_reading{job=\"$cluster\"}",
     "legendFormat": "agent[{{host}}]"
    },
    {
     "expr": "openc3_job_reading{job=\"$cluster\"}",
     "legendFormat": "job[{{host}}]"
    },
    {
     "expr": "openc3_jobx_reading{job=\"$cluster\"}",
     "legendFormat": "jobx[{{host}}]"
    },
    {
     "expr": "openc3_connector_reading{job=\"$cluster\"}",
     "legendFormat": "connector[{{host}}]"
    }
   ]
  },
  {
   "title": "writing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_api_writing{job=\"$cluster\"}",
     "legendFormat": "api[{{host}}]"
    },
    {
     "expr": "openc3_ci_writing{job=\"$cluster\"}",
     "legendFormat": "ci[{{host}}]"
    },
    {
     "expr": "openc3_agent_writing{job=\"$cluster\"}",
     "legendFormat": "agent[{{host}}]"
    },
    {
     "expr": "openc3_job_writing{job=\"$cluster\"}",
     "legendFormat": "job[{{host}}]"
    },
    {
     "expr": "openc3_jobx_writing{job=\"$cluster\"}",
     "legendFormat": "jobx[{{host}}]"
    },
    {
     "expr": "openc3_connector_writing{job=\"$cluster\"}",
     "legendFormat": "connector[{{host}}]"
    }
   ]
  },
  {
   "title": "waiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_api_waiting{job=\"$cluster\"}",
     "legendFormat": "api[{{host}}]"
    },
    {
     "expr": "openc3_ci_waiting{job=\"$cluster\"}",
     "legendFormat": "ci[{{host}}]"
    },
    {
     "expr": "openc3_agent_waiting{job=\"$cluster\"}",
     "legendFormat": "agent[{{host}}]"
    },
    {
     "expr": "openc3_job_waiting{job=\"$cluster\"}",
     "legendFormat": "job[{{host}}]"
    },
    {
     "expr": "openc3_jobx_waiting{job=\"$cluster\"}",
     "legendFormat": "jobx[{{host}}]"
    },
    {
     "expr": "openc3_connector_waiting{job=\"$cluster\"}",
     "legendFormat": "connector[{{host}}]"
    }
   ]
  },
  {
   "title": "接受请求/每分钟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openc3_api_accepts{job=\"$cluster\"}[1m])*60",
     "legendFormat": "api[{{host}}]"
    },
    {
     "expr": "rate(openc3_ci_accepts{job=\"$cluster\"}[1m])*60",
     "legendFormat": "ci[{{host}}]"
    },
    {
     "expr": "rate(openc3_agent_accepts{job=\"$cluster\"}[1m])*60",
     "legendFormat": "agent[{{host}}]"
    },
    {
     "expr": "rate(openc3_job_accepts{job=\"$cluster\"}[1m])*60",
     "legendFormat": " job[{{host}}]"
    },
    {
     "expr": "rate(openc3_jobx_accepts{job=\"$cluster\"}[1m])*60",
     "legendFormat": "jobx[{{host}}]"
    },
    {
     "expr": "rate(openc3_connector_accepts{job=\"$cluster\"}[1m])*60",
     "legendFormat": "connector[{{host}}]"
    }
   ]
  },
  {
   "title": "nginx状态",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_api_status{job=\"$cluster\"}",
     "legendFormat": "api[{{host}}]"
    },
    {
     "expr": "openc3_ci_status{job=\"$cluster\"}",
     "legendFormat": "ci[{{host}}]"
    },
    {
     "expr": "openc3_agent_status{job=\"$cluster\"}",
     "legendFormat": "agent[{{host}}]"
    },
    {
     "expr": "openc3_job_status{job=\"$cluster\"}",
     "legendFormat": "job[{{host}}]"
    },
    {
     "expr": "openc3_jobx_status{job=\"$cluster\"}",
     "legendFormat": "jobx[{{host}}]"
    },
    {
     "expr": "openc3_connector_status{job=\"$cluster\"}",
     "legendFormat": "connector[{{host}}]"
    }
   ]
  },
  {
   "title": "CI 项目数量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_ci_app_project_total{job=\"$cluster\"}",
     "legendFormat": "项目总量"
    },
    {
     "expr": "openc3_ci_app_project_active{job=\"$cluster\"}",
     "legendFormat": "有效项目量"
    }
   ]
  },
  {
   "title": "CI 运行中",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_ci_app_build_running{job=\"$cluster\"}",
     "legendFormat": "构建运行中"
    }
   ]
  },
  {
   "title": "CI构建失败总量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_ci_app_build_fail{job=\"$cluster\"}",
     "legendFormat": "构建失败总量"
    }
   ]
  },
  {
   "title": "CI 构建情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_ci_app_build_success{job=\"$cluster\"}",
     "legendFormat": "构建成功总量"
    },
    {
     "expr": "openc3_ci_app_build_total{job=\"$cluster\"}",
     "legendFormat": "发现tag总量"
    }
   ]
  },
  {
   "title": "JOBX 任务总量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_jobx_app_task_total{job=\"$cluster\"}",
     "legendFormat": "任务总量"
    }
   ]
  },
  {
   "title": "JOBX 运行中",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_jobx_app_subtask_next{job=\"$cluster\"}",
     "legendFormat": "subtask_next"
    },
    {
     "expr": "openc3_jobx_app_subtask_runnigs{job=\"$cluster\"}",
     "legendFormat": "subtask_runnigs"
    },
    {
     "expr": "openc3_jobx_app_subtask_decision{job=\"$cluster\"}",
     "legendFormat": "subtask_decision"
    },
    {
     "expr": "openc3_jobx_app_subtask_ignore{job=\"$cluster\"}",
     "legendFormat": "subtask_ignore"
    },
    {
     "expr": "openc3_jobx_app_task_running{job=\"$cluster\"}",
     "legendFormat": "task_running"
    }
   ]
  },
  {
   "title": "JOBX 失败总量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_jobx_app_task_fail{job=\"$cluster\"}",
     "legendFormat": "失败任务总量"
    },
    {
     "expr": "openc3_jobx_app_subtask_fail{job=\"$cluster\"}",
     "legendFormat": "失败子任务总量"
    }
   ]
  },
  {
   "title": "JOBX 子任务总量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_jobx_app_subtask_total{job=\"$cluster\"}",
     "legendFormat": "子任务总量"
    }
   ]
  },
  {
   "title": "JOB 任务总量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_job_app_task_total{job=\"$cluster\"}",
     "legendFormat": "任务总量"
    }
   ]
  },
  {
   "title": "JOB 运行中",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_job_app_subtask_next{job=\"$cluster\"}",
     "legendFormat": "subtask_next"
    },
    {
     "expr": "openc3_job_app_subtask_runnigs{job=\"$cluster\"}",
     "legendFormat": "subtask_runnigs"
    },
    {
     "expr": "openc3_job_app_subtask_ignore{job=\"$cluster\"}",
     "legendFormat": "subtask_ignore"
    },
    {
     "expr": "openc3_job_app_subtask_decision{job=\"$cluster\"}",
     "legendFormat": "subtask_decision"
    },
    {
     "expr": "openc3_job_app_task_running{job=\"$cluster\"}",
     "legendFormat": "task_running"
    }
   ]
  },
  {
   "title": "JOB 失败总量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_job_app_task_fail{job=\"$cluster\"}",
     "legendFormat": "失败任务总量"
    },
    {
     "expr": "openc3_job_app_subtask_fail{job=\"$cluster\"}",
     "legendFormat": "失败子任务总量"
    }
   ]
  },
  {
   "title": "JOB 子任务总量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_job_app_subtask_total{job=\"$cluster\"}",
     "legendFormat": "子任务总量"
    }
   ]
  },
  {
   "title": "AGENT & PROXY 总量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_app_proxy_total{job=\"$cluster\"}",
     "legendFormat": "代理总量"
    },
    {
     "expr": "openc3_agent_app_agent_total{job=\"$cluster\"}",
     "legendFormat": "Agent总量"
    }
   ]
  },
  {
   "title": "AGENT & PROXY  失败数量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_app_agent_fail{job=\"$cluster\"}",
     "legendFormat": "Agent失败总量"
    },
    {
     "expr": "openc3_agent_app_proxy_fail{job=\"$cluster\"}",
     "legendFormat": "代理失败总量"
    }
   ]
  },
  {
   "title": "AGENT 检测状态的项目数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_app_check_total{job=\"$cluster\"}",
     "legendFormat": "开启Agent检测的数量"
    }
   ]
  },
  {
   "title": "AGENT 进程",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_server_bury{job=\"$cluster\"}",
     "legendFormat": "bury[{{host}}]"
    },
    {
     "expr": "openc3_agent_server_call{job=\"$cluster\"}",
     "legendFormat": "call[{{host}}]"
    },
    {
     "expr": "openc3_agent_server_check{job=\"$cluster\"}",
     "legendFormat": "check[{{host}}]"
    },
    {
     "expr": "openc3_agent_server_inherit{job=\"$cluster\"}",
     "legendFormat": "inherit[{{host}}]"
    },
    {
     "expr": "openc3_agent_server_keepalive{job=\"$cluster\"}",
     "legendFormat": "keepalive[{{host}}]"
    }
   ]
  },
  {
   "title": "CI 进程",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_ci_server_build{job=\"$cluster\"}",
     "legendFormat": "build[{{host}}]"
    },
    {
     "expr": "openc3_ci_server_bury{job=\"$cluster\"}",
     "legendFormat": "bury[{{host}}]"
    },
    {
     "expr": "openc3_ci_server_clean{job=\"$cluster\"}",
     "legendFormat": "clean[{{host}}]"
    },
    {
     "expr": "openc3_ci_server_findtags{job=\"$cluster\"}",
     "legendFormat": "findtags[{{host}}]"
    },
    {
     "expr": "openc3_ci_server_keepalive{job=\"$cluster\"}",
     "legendFormat": "keepalive[{{host}}]"
    },
    {
     "expr": "openc3_ci_server_pkgrsync{job=\"$cluster\"}",
     "legendFormat": "pkgrsync[{{host}}]"
    }
   ]
  },
  {
   "title": "JOBX 进程",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_jobx_server_bury{job=\"$cluster\"}",
     "legendFormat": "buru[{{host}}]"
    },
    {
     "expr": "openc3_jobx_server_call{job=\"$cluster\"}",
     "legendFormat": "call[{{host}}]"
    },
    {
     "expr": "openc3_jobx_server_keepalive{job=\"$cluster\"}",
     "legendFormat": "keepalive[{{host}}]"
    },
    {
     "expr": "openc3_jobx_server_monitor{job=\"$cluster\"}",
     "legendFormat": "monitor[{{host}}]"
    }
   ]
  },
  {
   "title": "JOB 进程",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_job_server_approval{job=\"$cluster\"}",
     "legendFormat": "approval[{{host}}]"
    },
    {
     "expr": "openc3_job_server_bury{job=\"$cluster\"}",
     "legendFormat": "bury[{{host}}]"
    },
    {
     "expr": "openc3_job_server_call{job=\"$cluster\"}",
     "legendFormat": "call[{{host}}]"
    },
    {
     "expr": "openc3_job_server_clean{job=\"$cluster\"}",
     "legendFormat": "clean[{{host}}]"
    },
    {
     "expr": "openc3_job_server_crontab{job=\"$cluster\"}",
     "legendFormat": "crontab[{{host}}]"
    },
    {
     "expr": "openc3_job_server_keepalive{job=\"$cluster\"}",
     "legendFormat": "keepalive[{{host}}]"
    },
    {
     "expr": "openc3_job_server_notify{job=\"$cluster\"}",
     "legendFormat": "notify[{{host}}]"
    }
   ]
  },
  {
   "title": "API 进程",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_api{job=\"$cluster\"}",
     "legendFormat": "agent[{{host}}]"
    },
    {
     "expr": "openc3_ci_api{job=\"$cluster\"}",
     "legendFormat": "ci[{{host}}]"
    },
    {
     "expr": "openc3_job_api{job=\"$cluster\"}",
     "legendFormat": "job[{{host}}]"
    },
    {
     "expr": "openc3_jobx_api{job=\"$cluster\"}",
     "legendFormat": "jobx[{{host}}]"
    },
    {
     "expr": "openc3_connector_api{job=\"$cluster\"}",
     "legendFormat": "connector[{{host}}]"
    }
   ]
  },
  {
   "title": "supervisor守护进程",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_supervisor{job=\"$cluster\"}",
     "legendFormat": "agent[{{host}}]"
    },
    {
     "expr": "openc3_ci_supervisor{job=\"$cluster\"}",
     "legendFormat": "ci[{{host}}]"
    },
    {
     "expr": "openc3_job_supervisor{job=\"$cluster\"}",
     "legendFormat": "job[{{host}}]"
    },
    {
     "expr": "openc3_jobx_supervisor{job=\"$cluster\"}",
     "legendFormat": "jobx[{{host}}]"
    },
    {
     "expr": "openc3_connector_supervisor{job=\"$cluster\"}",
     "legendFormat": "connector[{{host}}]"
    }
   ]
  },
  {
   "title": "操作系统磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_os_disk_data{job=\"$cluster\"}",
     "legendFormat": "[{{host}}]:/data"
    },
    {
     "expr": "openc3_os_disk_root{job=\"$cluster\"}",
     "legendFormat": "[{{host}}]:/"
    },
    {
     "expr": "openc3_os_disk_glusterfs{job=\"$cluster\"}",
     "legendFormat": "[{{host}}]:/data/glusterfs"
    }
   ]
  },
  {
   "title": "操作系统负载",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_os_load{job=\"$cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Mysql 读/秒",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openc3_agent_mysql_read{job=\"$cluster\"}[1m])",
     "legendFormat": "agent"
    },
    {
     "expr": "rate(openc3_ci_mysql_read{job=\"$cluster\"}[1m])",
     "legendFormat": "ci"
    },
    {
     "expr": "rate(openc3_job_mysql_read{job=\"$cluster\"}[1m])",
     "legendFormat": "job"
    },
    {
     "expr": "rate(openc3_jobx_mysql_read{job=\"$cluster\"}[1m])",
     "legendFormat": "jobx"
    }
   ]
  },
  {
   "title": "Mysql 写/每秒",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(openc3_agent_mysql_write{job=\"$cluster\"}[10m])*60",
     "legendFormat": "agent"
    },
    {
     "expr": "rate(openc3_ci_mysql_write{job=\"$cluster\"}[10m])*60",
     "legendFormat": "ci"
    },
    {
     "expr": "rate(openc3_job_mysql_write{job=\"$cluster\"}[10m])*60",
     "legendFormat": "job"
    },
    {
     "expr": "rate(openc3_jobx_mysql_write{job=\"$cluster\"}[10m])*60",
     "legendFormat": "jobx"
    }
   ]
  },
  {
   "title": "Mysql 慢查询总量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_mysql_slow_queries{job=\"$cluster\"}",
     "legendFormat": "agent"
    },
    {
     "expr": "openc3_ci_mysql_slow_queries{job=\"$cluster\"}",
     "legendFormat": "ci"
    },
    {
     "expr": "openc3_job_mysql_slow_queries{job=\"$cluster\"}",
     "legendFormat": "job"
    },
    {
     "expr": "openc3_jobx_mysql_slow_queries{job=\"$cluster\"}",
     "legendFormat": "jobx"
    }
   ]
  },
  {
   "title": "Mysql 连接数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_mysql_threads_connected{job=\"$cluster\"}",
     "legendFormat": "agent"
    },
    {
     "expr": "openc3_ci_mysql_threads_connected{job=\"$cluster\"}",
     "legendFormat": "ci"
    },
    {
     "expr": "openc3_job_mysql_threads_connected{job=\"$cluster\"}",
     "legendFormat": "job"
    },
    {
     "expr": "openc3_jobx_mysql_threads_connected{job=\"$cluster\"}",
     "legendFormat": "jobx"
    }
   ]
  },
  {
   "title": "Mysql 连接池使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "openc3_agent_mysql_buffer_pool_use{job=\"$cluster\"}",
     "legendFormat": "agent"
    },
    {
     "expr": "openc3_ci_mysql_buffer_pool_use{job=\"$cluster\"}",
     "legendFormat": "ci"
    },
    {
     "expr": "openc3_job_mysql_buffer_pool_use{job=\"$cluster\"}",
     "legendFormat": "job"
    },
    {
     "expr": "openc3_jobx_mysql_buffer_pool_use{job=\"$cluster\"}",
     "legendFormat": "jobx"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } }
 ]
}